version: '2'
services:
  graphite:
    image: 'graphiteapp/graphite-statsd'
    container_name: graphite
    restart: always
    ports:
      - '81:80'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
      - '2024:2024'
      - '2004:2004'
      - '2023:2023'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./log/graphite:/opt/graphite/storage/log
      - ./log/supervisor:/var/log/supervisor
  grafana:
    build: .
    container_name: grafana
    user: root
    ports:
      - '80:3000'
    volumes:
      - ./data/grafana:/opt/grafana/data
