{
 "title": "Docker Spark Server Metrics2",
 "description": "CollectD & Graphite Server Metrics Dashboard with  CPU, Memory, IO & Disk Stats",
 "tags": [ "collectd" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "prefix", "query": "collectd" },
   { "name": "server", "query": "$prefix.*" },
   { "name": "app", "label": "Application", "query": "spark.*" }
  ]
 },
 "panels": [
  {
   "title": "Available Entropy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(collectd.$server.entropy.entropy)"
    }
   ]
  },
  {
   "title": "5min Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries($prefix.$server.load.load.midterm)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "target": "minSeries($prefix.$server.uptime.uptime)"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "aggregate($prefix.spark_master_1_.users.users, 'count')"
    }
   ]
  },
  {
   "title": "CPU Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.interrupt), 'Interrupt')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.nice), 'nice')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.softirq), 'softirq')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.steal), 'steal')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.system), 'system')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.user), 'user')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.wait), 'wait')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.idle), 'idle')"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.memory.memory.{cached,free,buffered}, 4)"
    }
   ]
  },
  {
   "title": "Network Traffic/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(scale(perSecond($prefix.$server.interface.*.if_octets.rx), 8), 'in')"
    },
    {
     "target": "alias(scale(perSecond($prefix.$server.interface.*.if_octets.tx), 8), 'out')"
    }
   ]
  },
  {
   "title": "Network Packets/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(perSecond($prefix.$server.interface.*.if_packets.rx), 'in')"
    },
    {
     "target": "alias(perSecond($prefix.$server.interface.*.if_packets.tx), 'out')"
    }
   ]
  },
  {
   "title": "Network Errors/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "$prefix.$server.interface.eth0.if_errors.rx"
    },
    {
     "target": "$prefix.$server.interface.eth0.if_errors.tx"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.load.load.shortterm, 4)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "spark.$app.*.executor.filesystem.hdfs.write_ops"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "spark.$app.*.executor.filesystem.hdfs.read_ops"
    }
   ]
  },
  {
   "title": "Driver Heap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "spark.$app.driver.jvm.heap.usage"
    }
   ]
  },
  {
   "title": "Driver JVM Memory Pools Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "spark.$app.driver.jvm.pools.Code-Cache.usage"
    },
    {
     "target": "spark.$app.driver.jvm.pools.Compressed-Class-Space.usage"
    },
    {
     "target": "spark.$app.driver.jvm.pools.Metaspace.usage"
    },
    {
     "target": "spark.$app.driver.jvm.pools.PS-Eden-Space.usage"
    },
    {
     "target": "spark.$app.driver.jvm.pools.PS-Old-Gen.usage"
    },
    {
     "target": "spark.$app.driver.jvm.pools.PS-Survivor-Space.usage"
    }
   ]
  },
  {
   "title": "Active Tasks Per Executor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "spark.$app.*.executor.threadpool.activeTasks"
    }
   ]
  },
  {
   "title": "Completed Tasks Per Executor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "spark.$app.*.executor.threadpool.completeTasks"
    }
   ]
  },
  {
   "title": "Current Pool Size Per Executor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "spark.$app.*.executor.threadpool.currentPool_size"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "spark.$app.*.jvm.heap.usage" }
   ]
  },
  {
   "title": "Eden-Space Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "spark.$app.*.jvm.pools.PS-Eden-Space.usage"
    }
   ]
  },
  {
   "title": "Old-Gen Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "spark.$app.*.jvm.pools.PS-Old-Gen.usage"
    }
   ]
  }
 ]
}