{
 "title": "CollectD Server Metrics2",
 "description": "CollectD & Graphite Server Metrics Dashboard with  CPU, Memory, IO & Disk Stats",
 "tags": [ "collectd" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prefix", "query": "${VAR_PREFIX}" },
   { "name": "server", "query": "$prefix.*" },
   { "name": "app", "label": "Application", "query": "spark.*" }
  ]
 },
 "panels": [
  {
   "title": "Available Entropy",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(collectd.$server.entropy.entropy)"
    }
   ]
  },
  {
   "title": "5min Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries($prefix.$server.load.load.midterm)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "target": "minSeries($prefix.$server.uptime.uptime)"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries($prefix.$server.users.users)"
    }
   ]
  },
  {
   "title": "CPU Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.interrupt), 'Interrupt')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.nice), 'nice')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.softirq), 'softirq')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.steal), 'steal')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.system), 'system')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.user), 'user')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.wait), 'wait')"
    },
    {
     "target": "alias(averageSeries($prefix.$server.cpu.*.cpu.idle), 'idle')"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.memory.memory.{cached,free,buffered}, 4)"
    }
   ]
  },
  {
   "title": "Network Traffic/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(scale(perSecond($prefix.$server.interface.*.if_octets.rx), 8), 'in')"
    },
    {
     "target": "alias(scale(perSecond($prefix.$server.interface.*.if_octets.tx), 8), 'out')"
    }
   ]
  },
  {
   "title": "Network Packets/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(perSecond($prefix.$server.interface.*.if_packets.rx), 'in')"
    },
    {
     "target": "alias(perSecond($prefix.$server.interface.*.if_packets.tx), 'out')"
    }
   ]
  },
  {
   "title": "Network Errors/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "$prefix.$server.interface.eth0.if_errors.rx"
    },
    {
     "target": "$prefix.$server.interface.eth0.if_errors.tx"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.load.load.shortterm, 4)"
    }
   ]
  },
  {
   "title": "Process Fork/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond($prefix.$server.processes.fork_rate), 'new processes')"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.processes.ps_state.*, 4)"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond($prefix.$server.disk.*.disk_ops.read), 3)"
    },
    {
     "target": "$prefix.$server.df.*.df_complex.select metric"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond($prefix.$server.disk.*.disk_ops.write), 3)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.df.*.percent_bytes.used, 1, 3)"
    }
   ]
  }
 ]
}